In [3]:
import sys, os
sys.path.append('..')
from Data.TimeSeries import *

from Data import factors
from ETF.AAA import *
import Quandl
import pandas as pd
import matplotlib

%matplotlib inline

/Users/jianboxue/anaconda/lib/python2.7/site-packages/pandas/io/data.py:33: FutureWarning:
The pandas.io.data module is moved to a separate package (pandas-datareader) and will be removed from pandas in a future version.
After installing the pandas-datareader package (https://github.com/pydata/pandas-datareader), you can change the import ``from pandas.io import data, wb`` to ``from pandas_datareader import data, wb``.
  FutureWarning)

In [14]:
sector_tickers = [
            'GOOG/NYSEARCA_XLB',
            'GOOG/NYSEARCA_XLE',
            'GOOG/NYSEARCA_XLF',
            'GOOG/NYSEARCA_XLI',
            'GOOG/NYSEARCA_XLK',
            'GOOG/NYSEARCA_XLP',
            'GOOG/NYSEARCA_XLU',
            'GOOG/NYSEARCA_XLV',
            'GOOG/NYSEARCA_XLY'
            ]

spy_ticker = ['GOOG/NYSE_SPY']

dp = TimeSeries(Settings()).get_agg_data(sector_tickers+spy_ticker)

dp = dp.fillna(method='pad', axis=0)
dp = dp.fillna(method='bfill', axis=0)
dp = dp[:,'2000-01-01'::,:]
dp = dp.dropna()

In [16]:
rets = pd.DataFrame()
rets[1] = Portfolio1(dp).run_trading().portfolio_value

In [21]:
df_spy = dp[spy_ticker[0], :, :]
df_spy

                             open    high     low   close     volume   price
Date
2000-01-03 00:00:00+00:00  148.25  148.25  143.88  145.44    8164300  145.44
2000-01-04 00:00:00+00:00  143.53  144.06  139.64  139.75    8085300  139.75
2000-01-05 00:00:00+00:00  139.94  141.53  137.25  140.00   12177900  140.00
2000-01-06 00:00:00+00:00  139.62  141.50  138.88  139.56    6142800  139.56
2000-01-07 00:00:00+00:00  140.31  145.75  140.06  145.75    8066600  145.75
2000-01-10 00:00:00+00:00  146.25  146.91  145.03  146.38    5741200  146.38
2000-01-11 00:00:00+00:00  145.81  146.09  143.50  144.31    7433700  144.31
2000-01-12 00:00:00+00:00  144.59  144.59  142.88  143.06    6907700  143.06
2000-01-13 00:00:00+00:00  144.47  145.75  143.28  144.91    5156300  144.91
2000-01-14 00:00:00+00:00  146.53  147.47  145.97  146.97    7437300  146.97
2000-01-18 00:00:00+00:00  145.34  146.62  145.19  145.81    6488500  145.81
2000-01-19 00:00:00+00:00  145.31  146.47  145.00  146.25    6152900  146.25
2000-01-20 00:00:00+00:00  146.97  146.97  143.81  144.75    5800100  144.75
2000-01-21 00:00:00+00:00  145.50  145.50  144.06  144.44    6244800  144.44
2000-01-24 00:00:00+00:00  145.66  145.84  139.41  140.34    7896900  140.34
2000-01-25 00:00:00+00:00  140.52  141.62  139.00  141.16    9938500  141.16
2000-01-26 00:00:00+00:00  141.00  141.55  140.09  140.81    5158100  140.81
2000-01-27 00:00:00+00:00  141.84  142.22  138.12  140.31   10875400  140.31
2000-01-28 00:00:00+00:00  139.44  140.06  135.53  135.88   11916200  135.88
2000-01-31 00:00:00+00:00  135.81  139.67  135.00  139.56   10768700  139.56
2000-02-01 00:00:00+00:00  139.75  141.69  138.53  140.94    8423900  140.94
2000-02-02 00:00:00+00:00  141.28  142.25  140.38  141.06    6205900  141.06
2000-02-03 00:00:00+00:00  142.06  143.25  140.00  143.19    7997500  143.19
2000-02-04 00:00:00+00:00  143.19  144.00  142.12  142.59    4925400  142.59
2000-02-07 00:00:00+00:00  142.56  142.78  141.44  142.38    5846800  142.38
2000-02-08 00:00:00+00:00  143.97  144.56  143.62  144.31    4936500  144.31
2000-02-09 00:00:00+00:00  144.47  144.47  141.27  141.28    8511500  141.28
2000-02-10 00:00:00+00:00  141.62  142.56  140.88  141.56    6690600  141.56
2000-02-11 00:00:00+00:00  141.84  141.94  138.03  139.20    9848800  139.20
2000-02-14 00:00:00+00:00  139.78  139.78  138.31  139.50    8528800  139.50
...                           ...     ...     ...     ...        ...     ...
2016-01-28 00:00:00+00:00  189.96  190.20  187.16  189.11  142851654  189.11
2016-01-29 00:00:00+00:00  190.02  193.88  189.88  193.72  204034161  193.72
2016-02-01 00:00:00+00:00  192.53  194.58  191.84  193.65  133582159  193.65
2016-02-02 00:00:00+00:00  191.96  191.97  189.54  190.16  175500039  190.16
2016-02-03 00:00:00+00:00  191.41  191.78  187.10  191.30  204060878  191.30
2016-02-04 00:00:00+00:00  190.71  192.75  189.96  191.60  137261874  191.60
2016-02-05 00:00:00+00:00  190.99  191.67  187.20  187.95  178436180  187.95
2016-02-08 00:00:00+00:00  185.77  186.12  182.80  185.42  189248416  185.42
2016-02-09 00:00:00+00:00  183.36  186.94  183.20  185.43  179281791  185.43
2016-02-10 00:00:00+00:00  186.41  188.34  185.12  185.27  146910485  185.27
2016-02-11 00:00:00+00:00  182.34  184.10  181.09  182.86  214629542  182.86
2016-02-12 00:00:00+00:00  184.96  186.65  183.96  186.63  127093730  186.63
2016-02-16 00:00:00+00:00  188.77  189.81  187.63  189.78  115542766  189.78
2016-02-17 00:00:00+00:00  191.16  193.32  191.01  192.88  134203601  192.88
2016-02-18 00:00:00+00:00  193.20  193.27  191.72  192.09  101076515  192.09
2016-02-19 00:00:00+00:00  191.17  192.18  190.45  192.00  114081542  192.00
2016-02-22 00:00:00+00:00  193.87  194.95  193.79  194.78  101699014  194.78
2016-02-23 00:00:00+00:00  194.00  194.32  192.18  192.32  109902798  192.32
2016-02-24 00:00:00+00:00  190.63  193.53  189.32  193.20  149607920  193.20
2016-02-25 00:00:00+00:00  193.73  195.55  192.83  195.54  109183249  195.54
2016-02-26 00:00:00+00:00  196.57  196.68  194.90  195.09  128348228  195.09
2016-02-29 00:00:00+00:00  195.11  196.23  193.33  193.35  122448542  193.35
2016-03-01 00:00:00+00:00  195.01  198.21  194.45  198.11  139070843  198.11
2016-03-02 00:00:00+00:00  197.74  199.06  197.25  199.00  101264715  199.00
2016-03-03 00:00:00+00:00  198.79  199.80  198.11  199.78   94597431  199.78
2016-03-04 00:00:00+00:00  200.01  201.35  199.03  200.43  127953606  200.43
2016-03-07 00:00:00+00:00  199.34  201.07  199.25  200.59   99778790  200.59
2016-03-08 00:00:00+00:00  199.32  199.92  198.21  198.40  121952823  198.40
2016-03-09 00:00:00+00:00  199.36  199.79  198.43  199.38   94801213  199.38
2016-03-10 00:00:00+00:00  199.96  201.07  197.38  199.54  156838697  199.54

[4085 rows x 6 columns]